### ISSUE TITLE
Possible typo in 4.2

### ISSUE THREAD

**Issue by sahi1l** [RunestoneInteractive/fopp#102]
**Describe the bug**
Section 4.2 refers to "directory ~\Desktop\mycode\"; I assume the backslashes should be slashes.  (Unless this is meant to be DOS, but I don't think DOS has the ~ convention, does it?)

https://runestone.academy/runestone/static/fopp/PythonModules/intro-ModulesandGettingHelp.html

**Comment by dichha** [comment]
This issue seems to be fixed . Screen attached. 

![screen shot 2019-01-29 at 8 42 19 am](https://user-images.githubusercontent.com/6922153/51924968-e1b63680-23a2-11e9-89fe-69e829704a5a.png)


This issue can be closed.

**Comment by dbrucknr** [comment]
I was wondering if we could close this issue? There appears to be a fix in place.
