### ISSUE TITLE
The CodeLens example in Section 7.3 is using Python-2 style print statement

### ISSUE THREAD

**Issue by sahi1l** [RunestoneInteractive/fopp#113]
**Describe the bug**
The CodeLens example on Section 7.3 appears to be using Python2 to evaluate the print statements, outputting tuples instead of strings.

**To Reproduce**
1. Go to https://runestone.academy/runestone/static/fopp/Iteration/FlowofExecutionoftheforLoop.html
2. Click on the Forward button in the CodeLens example.
3. The program output says `('Hi ', 'Joe', '  Please come to my party on Saturday!')`

**Expected behavior**
It should say `Hi Joe  Please come to my party on Saturday!`

**Comment by Grantrd** [comment]
This issue appears to be solved. - Berea College Student
