### ISSUE TITLE
IDEA: Show some examples of range in Section 7.6

### ISSUE THREAD

**Issue by sahi1l** [RunestoneInteractive/fopp#114]
Section 7.6 (re)introduces the range command, but it would be nice if the students could get an example of what the range function returns.  A code window with lines like 
> `print(range(10))`
> `print(list(range(10))`
> `print(list(range(11))`
> `print(list(range(1,11))`

https://runestone.academy/runestone/static/fopp/Iteration/TheAccumulatorPattern.html

**Comment by sahi1l** [comment]
Although I forgot that Runestone will actually expand range(10) without the cast, so the first line would be misleading.

**Comment by EzraSkwarka** [comment]
It looks like this has been addressed in dichharai's pull, but the issue was left open.
Needs to be closed
