### ISSUE TITLE
Change page title depending on content inside

### ISSUE THREAD

**Issue by sahi1l** [RunestoneInteractive/fopp#120]
**Describe the bug**
When I'm using Instructor's mode, I often have several tabs open pointing to Grading, the Gradebook, etc.  Unfortunately, all the tabs look exactly the same; they are all titled "Runestone Interactive".  It would be great if the `<title>` of each page would be different, at least on the administrative side of things, like `Gradebook - Runestone Interactive`.  (Although I suppose students might want to have multiple tabs open as well, if they are working on one project but referring back to a previous chapter for reference.)

**Comment by Grantrd** [comment]
I believe this issue has been solved, in FOPP at least. - Berea College Student
