### ISSUE TITLE
"Previous list" referred to but not explained for ac8_11_3

### ISSUE THREAD

**Issue by sahi1l** [RunestoneInteractive/fopp#121]
**Describe the bug**
Problem (ac8_11_3) says "Starting with the list of the previous exercise, write Python statements to do the following:"  But the list in the previous example is a set of course names.  

Also, ac8_11_3 has a tab labelled "Answer" and one "Discussion", which none of the others do.

**To Reproduce**
1. Visit https://runestone.academy/runestone/static/adrian_ac101f18/TransformingSequences/Exercises.html
2. Scroll to Question 3.

**Expected behavior**
The initial list should be provided explicitly, and the Answer tab should be removed.

**Comment by bnmnetp** [comment]
Well it was just a list for them to start with.  What other random stuff would you like to have on the list?

**Comment by sahi1l** [comment]
You misunderstand: the question assumes that the starting list is [76, 92.3, 'hello', True, 4, 76], and it asks questions like 'Find the index of “hello”' and 'Insert the value “cat” at position 3'.  These won't work with any arbitrary list.

**Comment by qasema** [comment]
@bnmnetp this issue appears to be resolved

**Comment by qasema** [comment]
@bnmnetp 
![image](https://user-images.githubusercontent.com/68142980/121592005-2db02600-ca08-11eb-8c16-ae4484f817c9.png)

**Comment by bnmnetp** [comment]
Thanks @qasema I'll close it.
