### ISSUE TITLE
Confused error message in act_rot13_ac_1

### ISSUE THREAD

**Issue by sahi1l** [RunestoneInteractive/fopp#122]
**Describe the bug**
When I submit code for act_rot13_ac_1, one of the tests has the Note "you need a loan_total variable".

**To Reproduce**
1. Go to https://runestone.academy/runestone/static/adrian_ac101f18/TransformingSequences/encryption.html
2. Scroll down to act_rot13_ac_1
3. Click on "Save and Run"
4. Look at the last column of the table that appears.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Javascript Console**
Please check the javascript console for any error messages and include them here.

**Comment by bnmnetp** [comment]
fixed
