### ISSUE TITLE
Missing image file in 9.18

### ISSUE THREAD

**Issue by sahi1l** [RunestoneInteractive/fopp#123]
**Describe the bug**
The file
https://runestone.academy/runestone/static/adrian_ac101f18/TransformingSequences/luther.jpg, 
which is sought in act_ip_4 in section 9.18.

**To Reproduce**
1. Go to https://runestone.academy/runestone/static/adrian_ac101f18/TransformingSequences/image_processing.html
2. Scroll down to (act_ip_4)
3. Try to run the code.
4. See the error message that the above file is missing.

**Comment by bnmnetp** [comment]
Not missing,, just a typo.  I should have updated all of those to use the golden_gate.png file instead of the Luther Bell.

Done
