### ISSUE TITLE
Formula for sepia tone missing in 9.18

### ISSUE THREAD

**Issue by sahi1l** [RunestoneInteractive/fopp#124]
**Describe the bug**
Section 9.18 says "Here is another pretty standard filter for photos called “Sepia tone” It will remind you of the old-west photographer style images. The formula to convert a photo into sepia tone is as follows:" but then there is no formula.

**To Reproduce**
1. Go to https://runestone.academy/runestone/static/adrian_ac101f18/TransformingSequences/image_processing.html
2. Search for "sepia"
4. Do not see the missing formula.

**Comment by bnmnetp** [comment]
Here is the formula:

```
newR = (R × 0.393 + G × 0.769 + B × 0.189)
newG = (R × 0.349 + G × 0.686 + B × 0.168)
newB = (R × 0.272 + G × 0.534 + B × 0.131)
```

**Comment by bnmnetp** [comment]
fixed
