### ISSUE TITLE
Error in answer to seqmut-1-1 reference diagram multiple choice question

### ISSUE THREAD

**Issue by BergProfJ** [RunestoneInteractive/fopp#129]
**Describe the bug**
The textbook answer/autograder answer for seqmut-1-1 provides an incorrect answer, I believe. The answer should be, "Neither is the correct reference diagram," because the code

```
lst = ['mercury', 'venus', 'earth', 'mars', 'jupiter', 'saturn', 'uranus', 'neptune', 'pluto']
lst.remove('pluto')
first_three = lst[:2]
```
results in first_three referring to the list [mercury, venus] (i.e. the first two items in the list, not the first three, because of the exclusive nature of the right edge of the slice operator).

Perhaps the code should be changed to "first_three = lst[:3]"

**To Reproduce**
1. Go to https://runestone.academy/runestone/static/heidelberg_ac101f18/TransformingSequences/week4a1.html#chapter-assessment-aliases-and-references
2. Click on any answer to the question
3. See error

**Expected behavior**
I believe the correct answer to this question is, "Neither is the correct reference diagram."  

**Screenshots**
![image](https://user-images.githubusercontent.com/19495370/46827044-9c271c80-cd65-11e8-9010-f4e441328fbd.png)

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser Chrome
 - Version 69

**Javascript Console**
No errors.

**Comment by bnmnetp** [comment]
Good catch.  Yes I think we should change the code to lst[:3]

**Comment by bnmnetp** [comment]
@dichha Can you make a PR for this?

**Comment by EzraSkwarka** [comment]
This issue has been resolved and the issue needs to be closed.
