### ISSUE TITLE
Ch 22.5 ActiveCode 1 Popup won’t exit

### ISSUE THREAD

**Issue by afusa21** [RunestoneInteractive/fopp#136]
**Describe the bug**
In the ActiveCode box, hitting "Run" without adding code to the program causes a popup to appear that won't exit when "Cancel" is clicked. In Firefox, ticking the "Prevent this page from creating additional dialogs” box and clicking "OK" will make the dialogue box disappear, but then the "Run" button becomes greyed out and a “a web page is slowing down your browser” warning appears. In Chrome, there is no such box to tick and it is impossible to exit the dialogue box. 

**To Reproduce**
1. Go to https://runestone.academy/runestone/static/fopp/Inheritance/TamagotchiRevisited.html?highlight=tamagotchi
2. Click on the “Run” button
3. Click on the “Cancel” button on the popup
4. Click on the “OK” button on the popup
5. Tick the  “Prevent this page from creating additional dialogs” box (if using Firefox)
6. Click on “OK”
7. Click on “Run”

**Expected behavior**
When the dialogue box appears, clicking "Cancel" cases the box to disappear.

**Screenshots**
![fopp_22_5](https://user-images.githubusercontent.com/43281119/47600170-c38b0580-d971-11e8-81a9-bad11ba43989.png)

**Desktop (please complete the following information):**
-Windows 10, version 1803
-Firefox 62
-Chrome 69

**Comment by bnmnetp** [comment]
Why would you disable the popup?  That is the only way for the program to get input from the user?  We have no control over the behavior of the dialog box anyway.

**Comment by presnick** [comment]
Perhaps there is some misunderstanding. That program runs by repeatedly requesting input from the user, which it gets from the popup window. If you want the popups to go away, you have to enter the command Quit in the dialog box.

I think this should be clear to students if they've been going through the content in sequence, building up from the simpler versions of the Tamagotchi game presented previously.

**Comment by Grantrd** [comment]
I came across this issue, looking for one to fix, I believe this ticket can be closed.
