### ISSUE TITLE
Codebox in act_monte_6 has text in it [URGENT]

### ISSUE THREAD

**Issue by sahi1l** [RunestoneInteractive/fopp#137]
**Describe the bug**
Box act_monte_6 in 10.17, which should be a place for code, contains markdown text instead.

**To Reproduce**
1. Go to https://runestone.academy/runestone/static/adrian_ac101f18/Files/monte_carlo_simulations.html
2. Scroll down to act_monte_6.

**Comment by bnmnetp** [comment]
Just pushed a fix.  removed one little space!

**Comment by sahi1l** [comment]
The fix doesn't show up in my book, even after a rebuild. Will I get the change by Thursday?
