### ISSUE TITLE
Project directions/prose incorrectly displayed in ActiveCode window

### ISSUE THREAD

**Issue by BergProfJ** [RunestoneInteractive/fopp#139]
**Describe the bug**
In Sec 10.17 "Monte Carlo Simulations," ActiveCode box #6 (act_monte_6), the prose text and partial description of the problem statement is appearing within the ActiveCode box and not above it.
https://runestone.academy/runestone/static/heidelberg_ac101f18/Files/monte_carlo_simulations.html

It seems like this text should actually be part of the prompt that accompanies ActiveCode #7 (below it).

**To Reproduce**
1. Go to https://runestone.academy/runestone/static/heidelberg_ac101f18/Files/monte_carlo_simulations.html
2. Scroll down to 'ActiveCode 6: (act_monte_6)

**Expected behavior**
The prose should appear above the ActiveCode box, as it seems to be the prompt for the reader.

**Screenshots**
![image](https://user-images.githubusercontent.com/19495370/47823426-ab82ff80-dd3e-11e8-919a-b76451569f48.png)

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser Chrome
 - Version 70.0.3538.77

**Javascript Console**
Please check the javascript console for any error messages and include them here.

**Comment by BergProfJ** [comment]
My apologies--I rebuilt and it seems the issue is fixed.

**Comment by bnmnetp** [comment]
Thanks @BergProfJ Scott  beat you to this one by a couple of days!

Brad
