### ISSUE TITLE
Misspelling in act_sac_1

### ISSUE THREAD

**Issue by sahi1l** [RunestoneInteractive/fopp#140]
**Describe the bug**
A small thing but potentially confusing: in act_sac_1 on https://runestone.academy/runestone/static/fopp/Dictionaries/split_apply_combine.html, it says "Read the so_servey.csv file and produce a report".  The name of the file is so_survey.csv.

**Comment by dichha** [comment]
Seems like this bug is fixed -- cannot find "so_servey.csv". Screen shot attached. 
![screen shot 2019-01-18 at 3 31 12 pm](https://user-images.githubusercontent.com/6922153/51418060-2d144d80-1b36-11e9-997f-b0225242fae8.png)
So this PR can be closed.
