### ISSUE TITLE
The code in assess_ac23_5_2 always gives an error.

### ISSUE THREAD

**Issue by carbonjo** [RunestoneInteractive/fopp#144]
**Describe the bug**
The code in assess_ac23_5_2 always gives an error.

**To Reproduce**
Change "4" to a "2"

**Comment by dichha** [comment]
@carbonjo, could you please tell in which chapter (possibly with a link to the chapter) is this bug? 
Could not find anywhere in the codebase I am looking -- ac101 and FOPP. 
Thanks.

**Comment by carbonjo** [comment]
Hi Dichha,

It was so long ago that I do not remember where it is, but I think that
Brad fixed it back then.

Joaquin

**Comment by dichha** [comment]
Thanks Joaquin. 

This issue can be closed.
