### ISSUE TITLE
Various typos

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/fopp#148]
7.2. The for Loop
If we were drawing a hexagon, or an octogon, 

7.6. The Accumulator Pattern
We can utilize the range function in this situation as well. Previously, you’ve seen it used when we wanted to draw in turtle. There we used it to iterate a certain number of times. We can do more than that though. The range function takes at least one input - which should be an integer - and returns a list as long as your input. [Should that be you’re?]

Because the the range function is exclusive of the ending number, we have to use 11 as the function input. [repeated word]

7.7. Traversal and the for Loop: By Index
We can use Enumerate, a built-in Python function, to make this proccess easier because it allows us to loop through something and have an automatic counter.

8.11 Setting Up Conditionals 
To make sure that your code covers all of the conditions that you intend for it to cover, you should add comments for each clause that explains what that clause is meant to do. Then, you should add tests for each possible path that the program could go though. What leads to certain conditional statements being executed? Is that was you intended? (Should it say “what” instead of was?)

9.17.3. Password to Key (challenge)
implement the algorithm outlined above assuming that the user entered ‘python’ for their password. Store the key in a variable called ‘key’. For testing purposes we will assume that no spaces or punctuation are included in the alphabet or the password.

Should implement be capitalized?
Should the word python be password?

10.16. 🤔 Exploring Common Words and SETI
Calculate the total usage percentage for the top 10 words in the list. Store this result in a variable called top_10 At the same time calculate the percentage for teh bottom 10 words in the list and store that result in bottom_10

**Comment by Cortesj** [comment]
@bnmnetp This issue appears to be resolved in pull request #157. Should this be closed?
