### ISSUE TITLE
act_sac_5, 6, and 7 all have the same introductory text

### ISSUE THREAD

**Issue by sahi1l** [RunestoneInteractive/fopp#151]
**Describe the bug**
act_sac_5, 6, and 7 all start by saying "What is the most popular programming language for people that exercise 3-4 times per week.", which only belongs on act_sac_5.  (Also, there should be a question mark at the end of it.)

https://runestone.academy/runestone/static/adrian_ac101f18/Dictionaries/split_apply_combine.html

**Comment by EzraSkwarka** [comment]
Issue resolved.
Needs to be closed.
