### ISSUE TITLE
IDEA: Introduce AdvancedAccumulation etc (filter,zip,comprehensions) after tuple unpacking

### ISSUE THREAD

**Issue by yarikoptic** [RunestoneInteractive/fopp#199]
[AdvancedAccumulation](https://runestone.academy/runestone/static/fopp/AdvancedAccumulation/toctree.html) is currently the very last (23rd) chapter in the book. As far as I see it, with [chapter 13. Tuple Packing and Unpacking](https://runestone.academy/runestone/static/fopp/Tuples/toctree.html), which is needed for `zip` explanation/use-cases, students should be fully prepared to learn and take advantage of all the materials in 23.
What I encounter that many students who already had some familiarity with Python do use list comprehensions while doing exercises in (much) earlier chapters.  And I find it counter-productive to "untrain"/mandate them to not use this feature of the language since it does make code more expressive and efficient.
Therefore I would suggest to move 23 to follow 13, and as time goes adjust the following chapters examples/exercises to make use of them.
Related: #197 (no dict comprehensions)

**Comment by bnmnetp** [comment]
There is always such a temptation to move everything earlier in the book.  We are all anxious to get to the interesting stuff -- learning about neuroscience by programming for example!

However, the goals of FOPP are to server a broader audience.  Primarily our audience is students that are in high school or are undergraduates.  In both cases these students have never programmed before, and experience shows me that we are already pushing most of the through the material about as fast as we can.

So, your grad students are probably at a very different place on the learning spectrum that most of our students, and I have to keep that in mind when thinking about adding more material and moving more material earlier.

**Comment by yarikoptic** [comment]
Indeed, probably depending on the audience it could be a bit too early. I will then just adjust in my course version of the book

Cheers
