### ISSUE TITLE
spelling error "refered"

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/fopp#219]
Error reported in course fopp on page FunctionCalls by user phosid phosidney@gmail.com
spelled referred wrong -- spelt as refered

**Comment by natstall** [comment]
The location of this page is fopp/_sources/SimplePythonData/FunctionCalls.rst. It appears this issue has already been fixed.

**Comment by dbrucknr** [comment]
This issue ticket appears ready to be closed.
close #219
