### ISSUE TITLE
Unittests for some Chapter 2 questions

### ISSUE THREAD

**Issue by tluchko** [RunestoneInteractive/fopp#250]
I've posted some unit tests for Chapter 2 Exercises on FOPP.  A few have some light editing.  The question IDs are 

TL_365_ex_2_9
TL_365_ex_2_10
TL_365_ex_2_12
TL_365_ex_2_14

where I have added the prefix 'TL_365_' to the original ID.  Note that TL_365_ex_2_14 fixes a typo in an earlier version I submitted.

If you prefer me to post the source code directly, please let me know.

**Comment by bnmnetp** [comment]
Yes, copying the source code into the issue would save me a couple of steps.  Thanks.

**Comment by bnmnetp** [comment]
will be live on Saturday.
