### ISSUE TITLE
access_ac_2_1_1_12 unit test should look for hardcoding

### ISSUE THREAD

**Issue by sahi1l** [RunestoneInteractive/fopp#254]
**Describe the bug**
The unit test for question access_ac_2_1_1_12 needs to look for hardcoding.

**To Reproduce**
1. Go to question access_ac_2_1_1_12.
2. Add a second line `num_lst=30`
3. Press run
4. See how it gets full credit.

The unit test would either search for the number 30 and/or search for the len function.

**Comment by bnmnetp** [comment]
These are easy enough to add, and there are plenty of other questions on that page that should get a similar treatment.  I fixed this one by adding the line

```
self.assertFalse(re.search(r'num_lst\s*=\s*30', self.getEditorText()), "hardcode check”)
```

**Comment by EzraSkwarka** [comment]
I'm one of the Berea students, I've started work on this issue

**Comment by EzraSkwarka** [comment]
Pull request made

**Comment by dbrucknr** [comment]
Hey everyone,

I was just checking to see if there had been any updates or resolutions to this issue?
