### ISSUE TITLE
In the assignments tab, make #component-preview float

### ISSUE THREAD

**Issue by sahi1l** [RunestoneInteractive/fopp#260]
**Describe the feature request**
When I choose a problem for an assignment, I have to then scroll back up to see what the problem looks like. This makes scrolling through multiple problems tedious.

**To Fix**
Add the following line to CSS:
```#component-preview: 
margin-right: 20px;
position: fixed;
right: 0px;
max-height: 100%;
overflow-y: scroll;
top: 0px;
padding-top: 60px;
```
We should also add a close button to component-preview so it doesn't get in the way of stuff higher up on the window.

**Comment by bnmnetp** [comment]
Nice!

**Comment by bnmnetp** [comment]
Added this and a close button... Will be live shortly.
