### ISSUE TITLE
References to 'ParseError' instead of SyntaxError

### ISSUE THREAD

**Issue by alexmojaki** [RunestoneInteractive/fopp#275]
[Know Your Error Messages](https://runestone.academy/runestone/books/published/fopp/Debugging/KnowyourerrorMessages.html) has a section on '[ParseError](https://runestone.academy/runestone/books/published/fopp/Debugging/KnowyourerrorMessages.html#parseerror)'. I'm guessing this is an old Skulpt name for SyntaxError or something? There is no ParseError in regular python, and even now when you run the examples it says SyntaxError.

Same applies to thinkcspy. Not sure where this kind of shared problem is supposed to be reported.

**Comment by bnmnetp** [comment]
Here is fine, its a small team.

Yes, the ParseError was removed from skulpt at some point in the past and we just haven't updated the text.

**Comment by bnmnetp** [comment]
Updated FOPP.  will be published this weekend.
