### ISSUE TITLE
Potential typo in Sec 12.4 Activty 3 ShowEval (eval11_3_1) - indentation error

### ISSUE THREAD

**Issue by BergProfJ** [RunestoneInteractive/fopp#276]
**Describe the bug**
I believe there may be an indentation error (lack of indentation) in Activity 3 ShowEval (eval11_3_1). The activity is designed to lead students through the steps in a function invocation.  It appears as if the two statements that are part of the function hello2 aren't properly indented within the function.

**To Reproduce**
1. Go to 'https://runestone.academy/runestone/books/published/fopp/Functions/FunctionParameters.html.'
2. Scroll down to 'Activity 3 ShowEval (eval11_3_1)'
4. See error - incorrect indentation

**Expected behavior**
I believe the 'print' statements should be indented inside function 'hello2'

**Screenshots**
![image](https://user-images.githubusercontent.com/19495370/68164991-3be4b900-ff2c-11e9-95b0-b4039b7a1419.png)

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser: Chrome
 - Version: 78.0.3904.87

**Comment by bnmnetp** [comment]
Thanks for this report.

The source is indented, so I'll have to investigate what has changed to see why it is not displaying as indented.

I'm not sure that I like this showEval very much as it seems confusing that the first animation shows a function call resolving to a def, which is not correct.  I'll think about it and try to fix it up.

**Comment by dbrucknr** [comment]
Hey,

It looks like this issue has been fixed. 
https://runestone.academy/runestone/books/published/fopp/Functions/FunctionParameters.html
Shows that the indentation appears correct.

Can we close this issue?
