### ISSUE TITLE
Unittests for various problems

### ISSUE THREAD

**Issue by tluchko** [RunestoneInteractive/fopp#279]
Attached is a file with unittests for various FOPP problems.  I've only included only FOPP exercises and assessment problems.  I also have unittests for many contributed exercises, including those that I've written myself. Those additional problems all have a 'TL_365_' prefix but can send those in a file as well.

[unittests.rst.zip](https://github.com/RunestoneInteractive/fopp/files/3888313/unittests.rst.zip)

**Comment by Bryar-Frank** [comment]
Partially addressed by pull request 336.
Have finished ac 7_14_8, ac7_14_7, ac7_14_2, ac7_14_1, ac11_14_13, ac11_14_8, ac11_14_1, ac9_9_1. Working on last 4.

**Comment by constantinol** [comment]
Completed in pull request #337 
inserts unit tests for the last four exercises ch_cl_02, ex6_11_2, ex6_11_3, ex_3_4.
ex6_11_1 is no longer a question in fopp.

**Comment by bisterj** [comment]
@bnmnetp we believe this can be closed
