### ISSUE TITLE
typo on Kiva min and max problem

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/fopp#280]
Error reported in course IntroCP2019MrH on page kiva_statistics by user MrHolston iraholston@berkeley.net
Typo:
Hint: max and min are builting (x built in ?)

Python functions that you can use to find the minimum value or maximum value in any sequence.

**Comment by dbrucknr** [comment]
I see this as well. I've been trying to locate the files to help fix, but I'm having a hard time.

Link to page: https://runestone.academy/runestone/books/published/fopp/Projects/kiva_statistics.html#kiva-statistics

Paragraph:
"Store the amount of the minimum loan in min_loan and the amount of the maximum loan in max_loan Then, store the name of the country that received the largest loan in max_country and the smallest loan in min_country Hint: max and min are builting Python functions that you can use to find the minimum value or maximum value in any sequence."

**Comment by bnmnetp** [comment]
Thanks, I appreciate the help.

You will find the source for the projects in the ac101 branch of the repository.
