### ISSUE TITLE
Images for assessment problem aren't showing

### ISSUE THREAD

**Issue by tnbai** [RunestoneInteractive/fopp#309]
Two images used for an assessment problem aren't displaying properly. The images are for the first problem in the 9.16. Chapter Assessment - List Methods.

Runestone page: https://fopp.umsi.education/books/published/fopp/TransformingSequences/week4a1.html

Github file: https://github.com/RunestoneInteractive/fopp/blob/master/_sources/TransformingSequences/week4a1.rst

**Comment by bisterj** [comment]
Images show up for me in 9.16. Am I looking at the wrong question?

![image](https://user-images.githubusercontent.com/69654276/135001445-b4299f58-e154-442e-a6cd-4554e271bec6.png)
