### ISSUE TITLE
ac4_7_8 in Section 3.7.4. ValueError demonstrates the wrong type of error

### ISSUE THREAD

**Issue by GeekLad** [RunestoneInteractive/fopp#312]
According to the text in the textbook, the code in ac4_7_8 should generate the following error:

```ValueError: invalid literal for int() with base 10: '' on line: 4```

However, it has a NameError:

```NameError: name 'wait_time_int' is not defined on line 5```

**To Reproduce**
1. Go to https://fopp.umsi.education/books/published/fopp/Debugging/KnowyourerrorMessages.html
2. Scroll down to section **3.7.4. ValueError**
3. Click **Save & Run**
4. A `NameError `is generated instead of a `ValueError`

**Expected behavior**
A `ValueError` should be generated

**Screenshots**
![image](https://user-images.githubusercontent.com/143769/76965357-858dd900-68fa-11ea-91bf-b0f7fcb7515f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version Version 79.0.3945.88 (Official Build) (64-bit)

**Comment by bnmnetp** [comment]
You are not supposed to enter a value for the first prompt.  If you just click OK, as you are told to do in the text then you will get a ValueError on line 2 before you ever get to the name error.

**Comment by bnmnetp** [comment]
Even so, I'll fix line 5 so that the program runs correctly when given correct input.

**Comment by bnmnetp** [comment]
Done.
