### ISSUE TITLE
Cannot Delete Old Courses

### ISSUE THREAD

**Issue by jonnycomes** [RunestoneInteractive/fopp#366]
Hello,

I'm unable to delete old runestone courses. When I click on Delete from the Instructor Page for the course, I either get a 504 Gateway Time-out, or an Internal error

Ticket issued: [runestone/198.60.192.201.2023-08-18.17-17-47.495be19a-343f-4cdf-a028-27bfd681e740](https://runestone.academy/admin/default/ticket/runestone/198.60.192.201.2023-08-18.17-17-47.495be19a-343f-4cdf-a028-27bfd681e740)

This is happening for every old course I try to delete. Most are fopp courses, but not all. Here are a few of the specific course I'd like to delete:

fopp courses:

CSC-150-TH-22Spring
CSC-150-MWF-22Spring
CSC-150-TH-21Fall
CSC-150-MWF-21Fall

Blue Book Course:

Assessments-Comes

**Comment by ladanielson** [comment]
I am having the same issue.  Thank you!

**Comment by bnmnetp** [comment]
Deleting a course deletes everything about that course including all student work.  There are many many foreign keys in the database that causes cascades of deletes.  As we have added new question types to the database we have not kept pace in the delete course controller.  

If you are trying to delete the old courses for student privacy reasons, I can work on manually deleting what needs to be deleted.  If you are just trying to clean up your course list you can simply unenroll yourself.

**Comment by jonnycomes** [comment]
Thanks Brad! 

No need to work on deleting anything. I will remove any assignments I want to be private before unenrolling.
