### ISSUE TITLE
Sequence Mutation Exercises

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/fopp#61]
ac8_11_6 will require that the students use an if statement.  Conditionals are not introduced until the next chapter.  Move this exercise to conditionals

@laumurph

**Comment by laumurph** [comment]
Didn't we want to move conditionals before sequence mutation?

**Comment by bnmnetp** [comment]
I had asked that question in the doc but I don't see a resolution and conditionals still come after sequence mutation in the outline.  @presnick what do you think about the order??
