### ISSUE TITLE
Dictionary Exercises

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/fopp#65]
For consistency the section should be Exercises not Dictionary Exercises

combine extra exercsies with exercises

@laumurph

**Comment by laumurph** [comment]
I think this is corrected in the integrate Exercises pull request. The dictionary and dictionary accumulation exercises are combined along with the extra exercises.

**Comment by bnmnetp** [comment]
I just checked and I don't see those changes in any of the outstanding PR's

**Comment by bnmnetp** [comment]
I must be losing it.  I can see that is fixed in the latest build.
