### ISSUE TITLE
Order of SequenceMutation and Conditionals

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/fopp#72]
I think we ought to move Conditionals in front of SequenceMutation

Then we can re-use many more practice problems from the Lists and Strings chapters of thinkcspy.  We will need to reword them so they are not asking for a function but there are a lot of them.

**Comment by laumurph** [comment]
That sounds good to me! That should work well with our python fluency course as well.

**Comment by presnick** [comment]
Agree
