### ISSUE TITLE
Incorrect variable name in seq-11-2

### ISSUE THREAD

**Issue by BergProfJ** [RunestoneInteractive/fopp#99]
Steps to reproduce:

Incorrect variable name when Parsons problem is loaded (?)

**Comment by BergProfJ** [comment]
Incorrect variable name in this Parsons problem:

Variable "sentences" is a list of items, but the for loop iterates over (missing) variable "phrases"

**Comment by BergProfJ** [comment]
![seq-11-2](https://user-images.githubusercontent.com/19495370/44946171-f1fec100-adc4-11e8-926a-2f9fe410ec91.jpg)

**Comment by bnmnetp** [comment]
fixed.

Please provide a link to the page containing the error as it makes it a lot faster to track down.

Thanks
